#Make RDS files from output generated by CodeOcean Splatter simulations
data.dir <- "/Users/rchapple/Documents/Software/cNMF/CodeOcean/results_replicated/data/Part1_Simulations_K14/deloc_1.00/"

seeds <- c("13657", "18839", "19052", "22856", "9485")

for(s in seeds){
    data <- read.delim2(paste0(data.dir, "Seed_", s, "/data.csv"), sep = ',')
    data <- data[, -1]
    genes <- as.character(read.table(paste0(data.dir, "Seed_", s, "/data.columns.txt"), sep = ','))
    cells <- as.character(read.table(paste0(data.dir, "Seed_", s, "/data.index.txt"), sep = ','))
    rownames(data) <- cells
    colnames(data) <- genes

    saveRDS(data, file = paste0(data.dir, "Seed_", s, "/cnmf_input_deloc_1.00_Seed_", s, ".RDS"))
}

#Prepare simpuated input data for acNMF processing

library(textshape)
library(Seurat)
library(SeuratDisk)

data <- readRDS("cnmf_input_deloc_1.00_Seed_13657.RDS")
data <- as.data.frame(data)
dim(data)

#Randomly sample (with substitution) to split the data into two roughly equal parts
set.seed(37645)
dummy_sep <- rbinom(nrow(data), 1, 0.5)

sum(dummy_sep = 0)
sum(dummy_sep = 1)

split0 <- data[dummy_sep == 0, ]
split1 <- data[dummy_sep == 1, ]

dim(split0)
dim(split1)

saveRDS(split0, file = "cnmf_input_benchmark_split0.RDS")
saveRDS(split1, file = "cnmf_input_benchmark_split1.RDS")

split0 <- as.matrix(split0)
split1 <- as.matrix(split1)

split0 <- t(split0)
split1 <- t(split1)

dim(split0)
dim(split1)

head(rownames(split0))
head(colnames(split0))

head(rownames(split1))
head(colnames(split1))

s0 <- CreateSeuratObject(counts = split0)
s1 <- CreateSeuratObject(counts = split1)

s0
s1

SaveH5Seurat(s0, filename = "cnmf_input_benchmark_split0.h5Seurat")
SaveH5Seurat(s1, filename = "cnmf_input_benchmark_split1.h5Seurat")

Convert("cnmf_input_benchmark_split0.h5Seurat", dest = "h5ad", assay = "RNA")
Convert("cnmf_input_benchmark_split1.h5Seurat", dest = "h5ad", assay = "RNA")
